# entry
name: example
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'chaitin rivers token'
        required: true
      type:
        description: 'your host type'
        required: true

jobs:
  runner:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: collie
        if: ${{ inputs.token != '' && inputs.type != '' }}
        uses: dvkunion/Trickster@main
        with:
          token: ${{ inputs.token }}
          host_source: "github"
          host_type: "windows"
